### ISSUE TITLE
phoenix-jooq example: org.jooq.exception.DataAccessException: Syntax error

### ISSUE THREAD

**Issue by rsarawgi** [sequenceiq/sequenceiq-samples#10]
Hi,
I was trying to run the phoenix-jooq example and ran into the error below. There are single quotes around the tablename which causes the error. On googling, came across a post which said that may be the dialect that is being used is incorrect. Could anyone help with this?

Error Log:
Exception in thread "main" org.jooq.exception.DataAccessException: SQL [select * from `customers` as `c` join `orders` as `o` on (o.customer_id = c.id) where `o.amount` < ? order by `c.name` asc]; ERROR 601 (42P00): Syntax error. Unexpected char: '`'
	at org.jooq.impl.Utils.translate(Utils.java:1288)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:495)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:327)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:330)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2256)
	at com.sequenceiq.samples.phoenix.Query.selectUsersWithLessAmount(Query.java:25)
	at com.sequenceiq.samples.phoenix.Bootstrap.main(Bootstrap.java:13)
Caused by: org.apache.phoenix.exception.PhoenixParserException: ERROR 601 (42P00): Syntax error. Unexpected char: '`'
	at org.apache.phoenix.exception.PhoenixParserException.newException(PhoenixParserException.java:33)
	at org.apache.phoenix.parse.SQLParser.parseStatement(SQLParser.java:118)
	at org.apache.phoenix.jdbc.PhoenixStatement$PhoenixStatementParser.parseStatement(PhoenixStatement.java:913)
	at org.apache.phoenix.jdbc.PhoenixStatement.parseStatement(PhoenixStatement.java:994)
	at org.apache.phoenix.jdbc.PhoenixPreparedStatement.<init>(PhoenixPreparedStatement.java:96)
	at org.apache.phoenix.jdbc.PhoenixConnection.prepareStatement(PhoenixConnection.java:583)
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.jdbc.datasource.TransactionAwareDataSourceProxy$TransactionAwareInvocationHandler.invoke(TransactionAwareDataSourceProxy.java:240)
	at com.sun.proxy.$Proxy30.prepareStatement(Unknown Source)
	at org.jooq.impl.ProviderEnabledConnection.prepareStatement(ProviderEnabledConnection.java:112)
	at org.jooq.impl.SettingsEnabledConnection.prepareStatement(SettingsEnabledConnection.java:76)
	at org.jooq.impl.AbstractResultQuery.prepare(AbstractResultQuery.java:230)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:297)
	... 4 more
Caused by: java.lang.RuntimeException: Unexpected char: '`'
	at org.apache.phoenix.parse.PhoenixSQLLexer.mOTHER(PhoenixSQLLexer.java:3687)
	at org.apache.phoenix.parse.PhoenixSQLLexer.mTokens(PhoenixSQLLexer.java:4625)
	at org.antlr.runtime.Lexer.nextToken(Lexer.java:85)
	at org.antlr.runtime.BufferedTokenStream.fetch(BufferedTokenStream.java:143)
	at org.antlr.runtime.BufferedTokenStream.sync(BufferedTokenStream.java:137)
	at org.antlr.runtime.CommonTokenStream.consume(CommonTokenStream.java:71)
	at org.antlr.runtime.BaseRecognizer.match(BaseRecognizer.java:106)
	at org.apache.phoenix.parse.PhoenixSQLParser.select_node(PhoenixSQLParser.java:3741)
	at org.apache.phoenix.parse.PhoenixSQLParser.hinted_select_node(PhoenixSQLParser.java:3900)
	at org.apache.phoenix.parse.PhoenixSQLParser.oneStatement(PhoenixSQLParser.java:560)
	at org.apache.phoenix.parse.PhoenixSQLParser.statement(PhoenixSQLParser.java:466)
	at org.apache.phoenix.parse.SQLParser.parseStatement(SQLParser.java:108)
	... 17 more

**Comment by rsarawgi** [comment]
Actually, using "table" instead of "tablebyName" fixes the issue.
